### PR TITLE
Change VSTS

### PR DESCRIPTION
**Pull request by jespicas**
Change all VSTS execept link of current project

### Description

Has modified all files .MD and replaced VSTS or Visual Studio Team Services for Azure DevOps

### Review

- [x] Checked all changes is text, not links of self project.

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Good thing you've filled in the PR template :)

**Comment by marceloavf** [comment]
Hey @jespicas, I just reviewed it above, need to fix some links and I can reopen it and accept the PR.

**Comment by jespicas** [comment]
Hi @marceloavf  what links?

**Comment by jespicas** [comment]
@marceloavf I understand, will do a new change with new links.

**Pull request closed without merging**
